### ISSUE TITLE
Crashes site (critical error) on new WP version

### ISSUE THREAD

**Issue by brkncoyot3** [coinbase/coinbase-commerce-gravity-forms#6]
Can't enable it.

**Comment by technogenius27** [comment]
Same issue here. Using latest wordpress and GF. Crashes the whole site when activated.

**Comment by brkncoyot3** [comment]
Can we get some help on this?

**Comment by oa-coinbase** [comment]
Hi @brkncoyot3 @technogenius27 unfortunately we are moving towards deprecating support for this plugin repository as it hasn't captured enough audience for us to maintain it at this time. The dependency [php SDK](https://github.com/coinbase/coinbase-commerce-php) however will be kept alive. Feel free to clone this repository to make modifications for your use, or post any PR's you would like to fix for the php SDK to share with the community. Sorry we couldn't be more helpful at this time.
