### ISSUE TITLE
Redirect back does not show confirmation

### ISSUE THREAD

**Issue by akudrikov** [coinbase/coinbase-commerce-gravity-forms#7]
?gf_coinbase_return=1&lead_id=1&form_id=1

because of php operator precedense 
if (rgget(self::RETURN_PAGE_PARAM) && $form_id = rgget(self::FORM_ID_PARAM) && $lead_id = rgget(self::LEAD_ID_PARAM)) 

$form_id is boolean here. This case page to show form again instead of confirmation:
Fix using "and" instead or 
if (rgget(self::RETURN_PAGE_PARAM) && ($form_id = rgget(self::FORM_ID_PARAM)) && ($lead_id = rgget(self::LEAD_ID_PARAM))) {

**Comment by oa-coinbase** [comment]
Hi @akudrikov - unfortunately we are moving towards deprecating support for this plugin repository as it hasn't captured enough audience for us to maintain it at this time, although we may pick it up again in the future. The dependency [coinbase-commerce-php SDK](https://github.com/coinbase/coinbase-commerce-php) however will be kept alive. Feel free to clone this repository to make modifications for your use, or post any PR's you would like to fix for the php SDK to share with the community. Sorry we couldn't be more helpful at this time.
